### 1.1.6.5.4. P6.3 — Derivative on Polynomials

$$
D : \mathbb{P}_3 \to \mathbb{P}_3, \quad D(p) = p'
$$

$$
M_D = \begin{bmatrix} 0 & 1 & 0 & 0 \\ 0 & 0 & 2 & 0 \\ 0 & 0 & 0 & 3 \\ 0 & 0 & 0 & 0 \end{bmatrix}
$$

**Explanation:**

The derivative operator $D$ maps polynomials of degree $\leq 3$ to polynomials of degree $\leq 3$. Using the standard basis $B = \{1, x, x^2, x^3\}$, probing gives a nilpotent upper-triangular matrix $M_D$.

A nilpotent matrix satisfies $M_D^k = 0$ for some $k$. Here $M_D^4 = 0$, reflecting that applying the derivative four times to any polynomial of degree $\leq 3$ yields zero.

**Example:**

Probing with each basis element:

$$
D(1) = 0, \quad D(x) = 1, \quad D(x^2) = 2x, \quad D(x^3) = 3x^2
$$

Writing these outputs as coordinate vectors in the basis $\{1, x, x^2, x^3\}$:

$$
M_D = \begin{bmatrix} 0 & 1 & 0 & 0 \\ 0 & 0 & 2 & 0 \\ 0 & 0 & 0 & 3 \\ 0 & 0 & 0 & 0 \end{bmatrix}
$$

Verification: $D(2 + 3x - x^2 + 5x^3) = 3 - 2x + 15x^2$, i.e. $M_D \cdot [2, 3, -1, 5]^T = [3, -2, 15, 0]^T$.

In [ ]:
import sympy as sp

matrix_d = sp.Matrix([
    [0, 1, 0, 0],
    [0, 0, 2, 0],
    [0, 0, 0, 3],
    [0, 0, 0, 0]
])

print("M_D =")
sp.pprint(matrix_d)

polynomial_coefficients = sp.Matrix([2, 3, -1, 5])
derivative_coefficients = matrix_d * polynomial_coefficients

print(f"\nD(2 + 3x - x^2 + 5x^3) -> coefficients: {list(derivative_coefficients)}")
print(f"= {derivative_coefficients[0]} + {derivative_coefficients[1]}x + {derivative_coefficients[2]}x^2")

nilpotent_powers = [matrix_d ** power for power in range(1, 5)]

for power, matrix_power in enumerate(nilpotent_powers, start=1):
    is_zero = matrix_power == sp.zeros(4, 4)
    print(f"\nM_D^{power} = 0? {is_zero}")

M_D =
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]

D(2 + 3x - x² + 5x³) → coefficients: [ 3 -2 15  0]
= 3 + -2x + 15x²

M_D^1 = 0? False

M_D^2 = 0? False

M_D^3 = 0? False

M_D^4 = 0? True


**References:**

[📘 Savov, I. (2016). *No Bullshit Guide to Linear Algebra*, Problem P6.3.](https://minireference.com/static/excerpts/noBSLA_v2_preview.pdf)

---

[⬅️ Previous: P6.2 Transformation on Function Spaces](./03_p6_2_transformation_on_function_spaces.ipynb) | [Next: Eigenvalues ➡️](../../07_Theoretical_Linear_Algebra/01_eigenvalues_and_eigenvectors/01_eigenvalues.ipynb)