### 1.1.4.2. Row Operations

$$
\begin{aligned}
\mathcal{R}_\alpha &: R_i \leftarrow R_i + \alpha R_j \quad &\text{(add a multiple of one row to another)} \\
\mathcal{R}_\beta &: R_i \leftrightarrow R_j \quad &\text{(swap two rows)} \\
\mathcal{R}_\gamma &: R_i \leftarrow k R_i \quad &\text{(multiply a row by a constant)}
\end{aligned}
$$

**Explanation:**

Row operations manipulate the rows of an augmented matrix without changing the solution set.
Three types are allowed: adding a multiple of one row to another, swapping two rows, and multiplying a row by a nonzero constant.
These operations are the building blocks of Gauss–Jordan elimination.

**Example:**

Starting from the augmented matrix

$$
\left[\begin{array}{cc|c}
1 & 2 & 5 \\
3 & 9 & 21
\end{array}\right],
$$

apply $R_2 \leftarrow R_2 - 3R_1$:

$$
\left[\begin{array}{cc|c}
1 & 2 & 5 \\
0 & 3 & 6
\end{array}\right],
$$

then $R_2 \leftarrow \tfrac{1}{3}R_2$:

$$
\left[\begin{array}{cc|c}
1 & 2 & 5 \\
0 & 1 & 2
\end{array}\right],
$$

then $R_1 \leftarrow R_1 - 2R_2$:

$$
\left[\begin{array}{cc|c}
1 & 0 & 1 \\
0 & 1 & 2
\end{array}\right].
$$

The solution is $x_1 = 1$, $x_2 = 2$.

In [3]:
import numpy as np

augmented = np.array([
    [1, 2, 5],
    [3, 9, 21]
], dtype=float)

print("Initial augmented matrix:")
print(augmented)

augmented[1] = augmented[1] - 3 * augmented[0]
print("\nAfter R2 ← R2 - 3R1:")
print(augmented)

augmented[1] = augmented[1] / 3
print("\nAfter R2 ← (1/3)R2:")
print(augmented)

augmented[0] = augmented[0] - 2 * augmented[1]
print("\nAfter R1 ← R1 - 2R2 (RREF):")
print(augmented)

print("\nSolution: x1 =", augmented[0, 2], ", x2 =", augmented[1, 2])

Initial augmented matrix:
[[ 1.  2.  5.]
 [ 3.  9. 21.]]

After R2 ← R2 - 3R1:
[[1. 2. 5.]
 [0. 3. 6.]]

After R2 ← (1/3)R2:
[[1. 2. 5.]
 [0. 1. 2.]]

After R1 ← R1 - 2R2 (RREF):
[[1. 0. 1.]
 [0. 1. 2.]]

Solution: x1 = 1.0 , x2 = 2.0


**References:**

[📘 Savov, I. (2016). *No Bullshit Guide to Linear Algebra*, Section 4.1 "Row Operations."](https://minireference.com/static/excerpts/noBSLA_v2_preview.pdf)

---

[⬅️ Previous: Augmented Matrix](./01_augmented_matrix.ipynb) | [Next: Reduced Row Echelon Form ➡️](./03_reduced_row_echelon_form.ipynb)