### 1.1.7.2.4. Upper Triangular Matrices

$$
U = \begin{bmatrix} a_{11} & a_{12} & a_{13} \\ 0 & a_{22} & a_{23} \\ 0 & 0 & a_{33} \end{bmatrix}, \quad a_{ij} = 0 \;\text{if}\; i > j
$$

**Explanation:**

Upper triangular matrices have zero entries below the main diagonal. For lower triangular, entries above the diagonal are zero. The eigenvalues of a triangular matrix are its diagonal entries. Triangular systems are easy to solve via back-substitution.

**Example:**

$$
U = \begin{bmatrix} 1 & 4 & 56 \\ 0 & 5 & 14 \\ 0 & 0 & 3 \end{bmatrix}
$$

The eigenvalues are $\lambda_1 = 1$, $\lambda_2 = 5$, $\lambda_3 = 3$. The determinant is the product of the diagonal entries:

$$
\det(U) = 1 \cdot 5 \cdot 3 = 15
$$

In [1]:
import numpy as np

upper_triangular = np.array([[1, 4, 56],
                             [0, 5, 14],
                             [0, 0,  3]])

print("U =")
print(upper_triangular)

eigenvalues = np.linalg.eigvals(upper_triangular)
diagonal_entries = np.diag(upper_triangular)
print("\nEigenvalues:", eigenvalues)
print("Diagonal entries:", diagonal_entries)
print("Eigenvalues match diagonal:", np.allclose(sorted(eigenvalues), sorted(diagonal_entries)))

determinant = np.linalg.det(upper_triangular)
print("\nDeterminant:", determinant)
print("Product of diagonal:", np.prod(diagonal_entries))

U =
[[ 1  4 56]
 [ 0  5 14]
 [ 0  0  3]]

Eigenvalues: [1. 5. 3.]
Diagonal entries: [1 5 3]
Eigenvalues match diagonal: True

Determinant: 15.0
Product of diagonal: 15


**References:**

[📘 Savov, I. (2016). *No Bullshit Guide to Linear Algebra*, Section 7.2](https://minireference.com/)

---

[⬅️ Previous: Symmetric Matrices](./03_symmetric_matrices.ipynb) | [Next: Identity Matrix ➡️](./05_identity_matrix.ipynb)