### 1.1.7.2.5. Identity Matrix

$$
\mathbb{1}_n A = A \mathbb{1}_n = A, \quad \lambda = 1 \;\text{for all eigenvectors}
$$

**Explanation:**

The identity matrix $\mathbb{1}$ plays the role of multiplication by 1 for matrices. It is diagonal with ones on the diagonal. Any vector $\vec{v} \in \mathbb{R}^n$ is an eigenvector of $\mathbb{1}$ with eigenvalue $\lambda = 1$.

**Example:**

For $\mathbb{1}_3$ and any $A \in \mathbb{R}^{3 \times 3}$:

$$
\mathbb{1}_3 A = A
$$

Every standard basis vector $\vec{e}_i$ satisfies $\mathbb{1}_3 \vec{e}_i = 1 \cdot \vec{e}_i$.

In [1]:
import numpy as np

identity = np.eye(3)
print("I_3 =")
print(identity)

random_matrix = np.random.randn(3, 3)
print("\nI·A == A:", np.allclose(identity @ random_matrix, random_matrix))
print("A·I == A:", np.allclose(random_matrix @ identity, random_matrix))

eigenvalues = np.linalg.eigvals(identity)
print("\nEigenvalues:", eigenvalues)
print("All eigenvalues are 1:", np.allclose(eigenvalues, 1.0))

I_3 =
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

I·A == A: True
A·I == A: True

Eigenvalues: [1. 1. 1.]
All eigenvalues are 1: True


**References:**

[📘 Savov, I. (2016). *No Bullshit Guide to Linear Algebra*, Section 7.2](https://minireference.com/)

---

[⬅️ Previous: Upper Triangular Matrices](./04_upper_triangular.ipynb) | [Next: Orthogonal Matrices ➡️](./06_orthogonal_matrices.ipynb)