### 1.1.7.2.9. Permutation Matrices

$$
M_\pi = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 0 & 1 \\ 0 & 1 & 0 \end{bmatrix}
$$

**Explanation:**

Permutation matrices change the order of coefficients of a vector. An $n \times n$ permutation matrix contains $n$ ones in $n$ different columns and zeros elsewhere. The sign of a permutation corresponds to $\det(M_\pi)$: even permutations yield $+1$, odd permutations yield $-1$.

**Example:**

The permutation $\pi: \hat{e}_1 \to \hat{e}_1,\; \hat{e}_2 \to \hat{e}_3,\; \hat{e}_3 \to \hat{e}_2$:

$$
M_\pi \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} = \begin{bmatrix} 1 \\ 3 \\ 2 \end{bmatrix}
$$

$$
\det(M_\pi) = -1 \quad \text{(odd permutation)}
$$

In [2]:
import numpy as np

permutation_matrix = np.array([[1, 0, 0],
                               [0, 0, 1],
                               [0, 1, 0]])

test_vector = np.array([1, 2, 3])
permuted_vector = permutation_matrix @ test_vector

print("M_pi =")
print(permutation_matrix)
print("\nM_pi @ (1, 2, 3) =", permuted_vector)

determinant = np.linalg.det(permutation_matrix)
print("\ndet(M_pi):", np.round(determinant, 10))

orthogonality_product = permutation_matrix.T @ permutation_matrix
print("\nM_pi^T M_pi =")
print(np.round(orthogonality_product, 10))
print("M_pi^T M_pi == I:", np.allclose(orthogonality_product, np.eye(3)))

M_pi =
[[1 0 0]
 [0 0 1]
 [0 1 0]]

M_pi @ (1, 2, 3) = [1 3 2]

det(M_pi): -1.0

M_pi^T M_pi =
[[1 0 0]
 [0 1 0]
 [0 0 1]]
M_pi^T M_pi == I: True


**References:**

[📘 Savov, I. (2016). *No Bullshit Guide to Linear Algebra*, Section 7.2](https://minireference.com/)

---

[⬅️ Previous: Reflections](./08_reflections.ipynb) | [Next: Positive Matrices ➡️](./10_positive_matrices.ipynb)