### 1.1.7.2.12. Normal Matrices

$$
A^{\mathsf{T}}A = AA^{\mathsf{T}}, \quad A = O\Lambda O^{\mathsf{T}}
$$

**Explanation:**

A matrix $A$ is normal if $A^{\mathsf{T}}A = AA^{\mathsf{T}}$. Properties: (1) $\vec{v}$ is an eigenvector of $A$ if and only if it is an eigenvector of $A^{\mathsf{T}}$, (2) eigenvectors corresponding to distinct eigenvalues are orthogonal, (3) $A$ has a full set of linearly independent eigenvectors and is diagonalizable by an orthogonal matrix. Both orthogonal matrices ($O^{\mathsf{T}}O = I$) and symmetric matrices ($A^{\mathsf{T}} = A$) are normal.

**Example:**

Symmetric matrix:

$$
A = \begin{bmatrix} 4 & 1 \\ 1 & 3 \end{bmatrix}
$$

Verify normality:

$$
A^{\mathsf{T}}A = \begin{bmatrix} 4 & 1 \\ 1 & 3 \end{bmatrix} \begin{bmatrix} 4 & 1 \\ 1 & 3 \end{bmatrix} = \begin{bmatrix} 17 & 7 \\ 7 & 10 \end{bmatrix} = AA^{\mathsf{T}}
$$

In [1]:
import numpy as np

symmetric_matrix = np.array([[4, 1],
                             [1, 3]])

product_left = symmetric_matrix.T @ symmetric_matrix
product_right = symmetric_matrix @ symmetric_matrix.T

print("A^T A =")
print(product_left)
print("\nA A^T =")
print(product_right)
print("\nA^T A == A A^T:", np.allclose(product_left, product_right))

eigenvalues, eigenvectors = np.linalg.eigh(symmetric_matrix)
print("\nEigenvalues:", np.round(eigenvalues, 4))

orthogonal_matrix = eigenvectors
diagonal_matrix = np.diag(eigenvalues)
reconstructed = orthogonal_matrix @ diagonal_matrix @ orthogonal_matrix.T

print("\nO Lambda O^T =")
print(np.round(reconstructed, 10))
print("A == O Lambda O^T:", np.allclose(reconstructed, symmetric_matrix))

print("\nO^T O =")
print(np.round(orthogonal_matrix.T @ orthogonal_matrix, 10))
print("O is orthogonal:", np.allclose(orthogonal_matrix.T @ orthogonal_matrix, np.eye(2)))

A^T A =
[[17  7]
 [ 7 10]]

A A^T =
[[17  7]
 [ 7 10]]

A^T A == A A^T: True

Eigenvalues: [2.382 4.618]

O Lambda O^T =
[[4. 1.]
 [1. 3.]]
A == O Lambda O^T: True

O^T O =
[[1. 0.]
 [0. 1.]]
O is orthogonal: True


**References:**

[📘 Savov, I. (2016). *No Bullshit Guide to Linear Algebra*, Section 7.2](https://minireference.com/)

---

[⬅️ Previous: Projection Matrices](./11_projection_matrices.ipynb) | [Next: Abstract Vector Spaces ➡️](../03_abstract_vector_spaces/01_abstract_vector_spaces.ipynb)