### 1.1.3.4. Matrix Multiplication

$$
C = AB, \qquad c_{ij} = \sum_{k=1}^{\ell} a_{ik}\, b_{kj}
$$

$$
\begin{bmatrix} a & b \\ c & d \end{bmatrix}
\begin{bmatrix} e & f \\ g & h \end{bmatrix}
=
\begin{bmatrix}
ae + bg & af + bh \\
ce + dg & cf + dh
\end{bmatrix}
$$

**Explanation:**

The matrix product $AB$ is computed by taking the dot product between each row of $A$ and each column of $B$.
For the product to exist, the "touching" dimensions must match: if $A \in \mathbb{R}^{m \times \ell}$ and $B \in \mathbb{R}^{\ell \times n}$, then $C = AB \in \mathbb{R}^{m \times n}$.
It is used in ML for layer operations in neural networks and represents the composition of linear transformations.

**Properties:**
- Associative: $(AB)C = A(BC)$
- Not commutative: $AB \neq BA$ in general
- Distributive: $A(B + C) = AB + AC$
- Composition of linear transformations: $B \circ A$ corresponds to the product $BA$

**Example:**

$$
\underbrace{\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}}_{A \in \mathbb{R}^{2 \times 3}}
\underbrace{\begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{bmatrix}}_{B \in \mathbb{R}^{3 \times 2}}
=
\begin{bmatrix}
1+6+15 & 2+8+18 \\
4+15+30 & 8+20+36
\end{bmatrix}
=
\underbrace{\begin{bmatrix} 22 & 28 \\ 49 & 64 \end{bmatrix}}_{C \in \mathbb{R}^{2 \times 2}}.
$$

In [1]:
import numpy as np

matrix_a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

matrix_b = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

product_ab = matrix_a @ matrix_b
product_ba = matrix_b @ matrix_a

print("AB =")
print(product_ab)
print("\nBA =")
print(product_ba)
print("\nAB and BA have different dimensions:", product_ab.shape, "vs", product_ba.shape)

AB =
[[22 28]
 [49 64]]

BA =
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]

AB and BA have different dimensions: (2, 2) vs (3, 3)


**References:**

[📘 Aazi, M. (2024). *Mathematics For Machine Learning*](https://www.scribd.com/document/812294393/Mathematics-for-Machine-Learning)  
[📘 Savov, I. (2016). *No Bullshit Guide to Linear Algebra*, Section 4.3 "Matrix Multiplication."](https://minireference.com/static/excerpts/noBSLA_v2_preview.pdf)

---

[⬅️ Previous: Matrix-Vector Multiplication](./03_matrix_vector_multiplication.ipynb) | [Next: Transpose of a Matrix ➡️](./05_matrix_transpose.ipynb)