### 1.1.3.10. Inverse of a Square Matrix

$$
A^{-1} = \frac{1}{\det(A)} \operatorname{adj}(A)
$$

$$
\begin{bmatrix} a & b \\ c & d \end{bmatrix}^{-1}
= \frac{1}{ad - bc}
\begin{bmatrix} d & -b \\ -c & a \end{bmatrix}
$$

**Explanation:**

The inverse of a matrix $A$ exists if and only if $\det(A) \neq 0$.
Three methods can be used to compute the inverse: the adjugate matrix formula, Gauss–Jordan elimination on the extended array $[A \mid \mathbb{1}]$, and the product of elementary matrices.

**Method 1: Adjugate matrix formula**

$A^{-1} = \frac{1}{\det(A)} \operatorname{adj}(A)$, where $\operatorname{adj}(A) = C^\top$ is the transpose of the matrix of cofactors.

**Steps:**
1. Compute $\det(A)$. If $\det(A) = 0$, the matrix is not invertible.
2. Compute the cofactor matrix $C$: each entry $C_{ij} = (-1)^{i+j} M_{ij}$, where $M_{ij}$ is the minor.
3. Transpose the cofactor matrix to obtain $\operatorname{adj}(A) = C^\top$, then divide by $\det(A)$.

**Method 2: Gauss–Jordan elimination**

Initialize $[A \mid \mathbb{1}]$ and apply row operations until the left side becomes the identity:

$$
[A \mid \mathbb{1}] \;\xrightarrow{\text{G–J elimination}}\; [\mathbb{1} \mid A^{-1}]
$$

**Method 3: Elementary matrices**

If the row operations $\mathcal{R}_1, \mathcal{R}_2, \ldots, \mathcal{R}_k$ transform $A$ into $\mathbb{1}$, then $A^{-1} = E_k \cdots E_2 E_1$.


#### **Example: Inverse of 3×3 Matrix (Method 1)**

Let  

$$
\mathbf{A} =
\begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i
\end{bmatrix}
$$

**1st step**

$$
\det(\mathbf{A}) = aei + bfg + cdh - gec - hfa - idb \neq 0
$$

**2nd step**

For $i = 1$ and $j = 1$ (deletion of the first row and column):

$$
\mathbf{A} =
\begin{bmatrix}
\color{red}{a} & \color{red}{b} & \color{red}{c} \\
\color{red}{d} & e & f \\
\color{red}{g} & h & i
\end{bmatrix}
\Rightarrow
(-1)^{1+1}
\begin{vmatrix}
e & f \\
h & i
\end{vmatrix}
=
\begin{vmatrix}
e & f \\
h & i
\end{vmatrix}
$$

For $i = 1$ and $j = 2$ (deletion of the first row and second column):

$$
\mathbf{A} =
\begin{bmatrix}
\color{red}{a} & \color{red}{b} & \color{red}{c} \\
d & \color{red}{e} & f \\
g & \color{red}{h} & i
\end{bmatrix}
\Rightarrow
(-1)^{1+2}
\begin{vmatrix}
d & f \\
g & i
\end{vmatrix}
=
-
\begin{vmatrix}
d & f \\
g & i
\end{vmatrix}
$$

and so on for the remaining cofactors.


**3rd step**

$$
\mathbf{A}^{-1} = 
\frac{1}{\det(\mathbf{A})}
\begin{bmatrix}
\begin{vmatrix} e & f \\ h & i \end{vmatrix} &
-\begin{vmatrix} d & f \\ g & i \end{vmatrix} &
\begin{vmatrix} d & e \\ g & h \end{vmatrix} \\
-\begin{vmatrix} b & c \\ h & i \end{vmatrix} &
\begin{vmatrix} a & c \\ g & i \end{vmatrix} &
-\begin{vmatrix} a & c \\ d & f \end{vmatrix} \\
\begin{vmatrix} b & c \\ e & f \end{vmatrix} &
-\begin{vmatrix} a & c \\ d & f \end{vmatrix} &
\begin{vmatrix} a & b \\ d & e \end{vmatrix}
\end{bmatrix}^T
$$

Thus,

$$
\mathbf{A}^{-1} = 
\frac{1}{\det(\mathbf{A})}
\begin{bmatrix}
\begin{vmatrix} e & f \\ h & i \end{vmatrix} &
-\begin{vmatrix} b & c \\ h & i \end{vmatrix} &
\begin{vmatrix} b & c \\ e & f \end{vmatrix} \\
-\begin{vmatrix} d & f \\ g & i \end{vmatrix} &
\begin{vmatrix} a & c \\ g & i \end{vmatrix} &
-\begin{vmatrix} a & c \\ d & f \end{vmatrix} \\
\begin{vmatrix} d & e \\ g & h \end{vmatrix} &
-\begin{vmatrix} a & b \\ g & h \end{vmatrix} &
\begin{vmatrix} a & b \\ d & e \end{vmatrix}
\end{bmatrix}
$$


#### **Numerical Example**

Let  

$$
\mathbf{A} =
\begin{bmatrix}
2 & 1 & 0 \\
1 & 2 & 1 \\
0 & 1 & 2
\end{bmatrix}
$$

**1st step**

Using $\,\det(\mathbf{A}) = aei + bfg + cdh - gec - hfa - idb\,$:

$$
\det(\mathbf{A}) = (2)(2)(2) + (1)(1)(0) + (0)(1)(1)
- (0)(2)(0) - (1)(1)(2) - (2)(1)(1) = 8 - 2 - 2 = 4 \neq 0.
$$

**2nd step**

For $i=1,\ j=1$ (delete first row and first column):

$$
\mathbf{A} =
\begin{bmatrix}
\color{red}{2} & \color{red}{1} & \color{red}{0} \\
\color{red}{1} & 2 & 1 \\
\color{red}{0} & 1 & 2
\end{bmatrix}
\Rightarrow
\begin{vmatrix}
2 & 1 \\
1 & 2
\end{vmatrix}
= 3,
\qquad C_{11} = (+)3.
$$

For $i=1,\ j=2$ (delete first row and second column):

$$
\mathbf{A} =
\begin{bmatrix}
\color{red}{2} & \color{red}{1} & \color{red}{0} \\
1 & \color{red}{2} & 1 \\
0 & \color{red}{1} & 2
\end{bmatrix}
\Rightarrow
\begin{vmatrix}
1 & 1 \\
0 & 2
\end{vmatrix}
= 2,
\qquad C_{12} = (-)2 = -2.
$$

Proceeding similarly for all entries gives the **cofactor matrix**:

$$
\mathbf{C} =
\begin{bmatrix}
\;\,3 & -2 & \;\,1 \\
-2 & \;\,4 & -2 \\
\;\,1 & -2 & \;\,3
\end{bmatrix}.
$$

**3rd step**

The **adjugate** is the transpose of the cofactor matrix, here identical because $\mathbf{C}$ is symmetric:

$$
\operatorname{adj}(\mathbf{A}) = \mathbf{C}^T =
\begin{bmatrix}
3 & -2 & 1 \\
-2 & 4 & -2 \\
1 & -2 & 3
\end{bmatrix}.
$$

Therefore,

$$
\mathbf{A}^{-1}
= \frac{1}{\det(\mathbf{A})}\,\operatorname{adj}(\mathbf{A})
= \frac{1}{4}
\begin{bmatrix}
3 & -2 & 1 \\
-2 & 4 & -2 \\
1 & -2 & 3
\end{bmatrix}
=
\begin{bmatrix}
0.75 & -0.50 & 0.25 \\
-0.50 & 1.00 & -0.50 \\
0.25 & -0.50 & 0.75
\end{bmatrix}.
$$

In [5]:
import numpy as np

matrix = np.array([
    [2, 1, 0],
    [1, 2, 1],
    [0, 1, 2]
])

inverse = np.linalg.inv(matrix)
verification = matrix @ inverse

print("A =")
print(matrix)
print("\nA⁻¹ =")
print(np.round(inverse, 4))
print("\nA · A⁻¹ =")
print(np.round(verification, 4))

A =
[[2 1 0]
 [1 2 1]
 [0 1 2]]

A⁻¹ =
[[ 0.75 -0.5   0.25]
 [-0.5   1.   -0.5 ]
 [ 0.25 -0.5   0.75]]

A · A⁻¹ =
[[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0.  0.  1.]]


In [6]:
import sympy as sp

matrix = sp.Matrix([
    [2, 1, 0],
    [1, 2, 1],
    [0, 1, 2]
])

identity = sp.eye(3)
extended = matrix.row_join(identity)

print("Extended array [A | I]:")
sp.pprint(extended)

rref_result, _ = extended.rref()

print("\nAfter Gauss–Jordan elimination [I | A⁻¹]:")
sp.pprint(rref_result)

print("\nA⁻¹ (right side):")
sp.pprint(rref_result[:, 3:])

Extended array [A | I]:
⎡2  1  0  1  0  0⎤
⎢                ⎥
⎢1  2  1  0  1  0⎥
⎢                ⎥
⎣0  1  2  0  0  1⎦

After Gauss–Jordan elimination [I | A⁻¹]:
⎡1  0  0  3/4   -1/2  1/4 ⎤
⎢                         ⎥
⎢0  1  0  -1/2   1    -1/2⎥
⎢                         ⎥
⎣0  0  1  1/4   -1/2  3/4 ⎦

A⁻¹ (right side):
⎡3/4   -1/2  1/4 ⎤
⎢                ⎥
⎢-1/2   1    -1/2⎥
⎢                ⎥
⎣1/4   -1/2  3/4 ⎦


**References:**

[📘 Aazi, M. (2024). *Mathematics For Machine Learning*](https://www.scribd.com/document/812294393/Mathematics-for-Machine-Learning)  
[📗 Rozycki, P. (2020). *Notes from Computational Mechanics Program, École Centrale de Nantes*](https://www.ec-nantes.fr/study/masters/computational-mechanics)  
[📘 Savov, I. (2016). *No Bullshit Guide to Linear Algebra*, Section 4.5 "Matrix Inverse."](https://minireference.com/static/excerpts/noBSLA_v2_preview.pdf)

---

[⬅️ Previous: Determinant of a Triangular Matrix](./09_matrix_determinant.ipynb) | [Next: Rank–Nullity Theorem ➡️](./11_matrix_rank_nullity.ipynb)