### 1.1.3.19. Matrix Block Multiplication

$$
\mathbf{A}\mathbf{B} =
\begin{bmatrix}
\mathbf{A}_{11}\mathbf{B}_{11} + \mathbf{A}_{12}\mathbf{B}_{21} &
\mathbf{A}_{11}\mathbf{B}_{12} + \mathbf{A}_{12}\mathbf{B}_{22} \\
\mathbf{A}_{21}\mathbf{B}_{11} + \mathbf{A}_{22}\mathbf{B}_{21} &
\mathbf{A}_{21}\mathbf{B}_{12} + \mathbf{A}_{22}\mathbf{B}_{22}
\end{bmatrix}
$$

**Explanation:**

Block multiplication generalizes matrix multiplication by partitioning matrices into submatrices.
This simplifies analysis of large matrices, enables parallel computation, and is useful in numerical linear algebra and control systems.

**Example:**

Partition

$$
\mathbf{A} =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix},
\quad
\mathbf{B} =
\begin{bmatrix}
9 & 8 & 7 \\
6 & 5 & 4 \\
3 & 2 & 1
\end{bmatrix}
$$

into $2 \times 2$ block matrices by rows and columns.
Multiplying the blocks yields the same result as standard multiplication.

In [1]:
import numpy as np

block_a11 = np.array([[1, 2], [3, 4]])
block_a12 = np.array([[5, 6], [7, 8]])
block_a21 = np.array([[9, 10], [11, 12]])
block_a22 = np.array([[13, 14], [15, 16]])

block_b11 = np.array([[17, 18], [19, 20]])
block_b12 = np.array([[21, 22], [23, 24]])
block_b21 = np.array([[25, 26], [27, 28]])
block_b22 = np.array([[29, 30], [31, 32]])

top_left = block_a11 @ block_b11 + block_a12 @ block_b21
top_right = block_a11 @ block_b12 + block_a12 @ block_b22
bottom_left = block_a21 @ block_b11 + block_a22 @ block_b21
bottom_right = block_a21 @ block_b12 + block_a22 @ block_b22

result = np.block([
    [top_left, top_right],
    [bottom_left, bottom_right]
])

print("Block multiplication result:\n", result)

Block multiplication result:
 [[ 342  356  398  412]
 [ 518  540  606  628]
 [1046 1092 1230 1276]
 [1222 1276 1438 1492]]


**References:**

[📘 Aazi, M. (2024). *Mathematics For Machine Learning*](https://www.scribd.com/document/812294393/Mathematics-for-Machine-Learning)  

---

[⬅️ Previous: Trace of a Product](./18_matrix_trace_of_product.ipynb) | [Next: Kronecker Product ➡️](./20_matrix_kronecker_product.ipynb)
