### 1.1.3.18. Matrix Block Multiplication


Block multiplication generalizes matrix multiplication by partitioning matrices into submatrices.
Suppose

$$
\mathbf{A} =
\begin{bmatrix}
\mathbf{A}_{11} & \mathbf{A}_{12} \\
\mathbf{A}_{21} & \mathbf{A}_{22}
\end{bmatrix},
\quad
\mathbf{B} =
\begin{bmatrix}
\mathbf{B}_{11} & \mathbf{B}_{12} \\
\mathbf{B}_{21} & \mathbf{B}_{22}
\end{bmatrix},
$$

where the block dimensions are compatible.
Then

$$
\mathbf{A}\mathbf{B} =
\begin{bmatrix}
\mathbf{A}_{11}\mathbf{B}_{11} + \mathbf{A}_{12}\mathbf{B}_{21} &
\mathbf{A}_{11}\mathbf{B}_{12} + \mathbf{A}_{12}\mathbf{B}_{22} \\
\mathbf{A}_{21}\mathbf{B}_{11} + \mathbf{A}_{22}\mathbf{B}_{21} &
\mathbf{A}_{21}\mathbf{B}_{12} + \mathbf{A}_{22}\mathbf{B}_{22}
\end{bmatrix}.
$$


#### **Benefits**

- Simplifies analysis of large matrices.
- Enables parallel computation by working on blocks independently.
- Useful in numerical linear algebra and control systems.


#### **Example**

Partition

$$
\mathbf{A} =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix},
\quad
\mathbf{B} =
\begin{bmatrix}
9 & 8 & 7 \\
6 & 5 & 4 \\
3 & 2 & 1
\end{bmatrix}
$$

into $2 \times 2$ block matrices by rows and columns.
Multiplying the blocks yields the same result as standard multiplication.

In [5]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 10], [11, 12]])
D = np.array([[13, 14], [15, 16]])

E = np.array([[17, 18], [19, 20]])
F = np.array([[21, 22], [23, 24]])
G = np.array([[25, 26], [27, 28]])
H = np.array([[29, 30], [31, 32]])

top_left = np.dot(A, E) + np.dot(B, G)
top_right = np.dot(A, F) + np.dot(B, H)
bottom_left = np.dot(C, E) + np.dot(D, G)
bottom_right = np.dot(C, F) + np.dot(D, H)

result = np.block([[top_left, top_right],
                   [bottom_left, bottom_right]])

print("Block Matrix Result:\n", result)


Block Matrix Result:
 [[ 342  356  398  412]
 [ 518  540  606  628]
 [1046 1092 1230 1276]
 [1222 1276 1438 1492]]


**References:**

[📘 Aazi, M. (2024). *Mathematics For Machine Learning*](https://www.scribd.com/document/812294393/Mathematics-for-Machine-Learning)  

---

[⬅️ Previous: Trace of a Product](./17_matrix_trace_of_product.ipynb) | [Next: Kronecker Product ➡️](./19_matrix_kronecker_product.ipynb)
