### 1.1.1.6. Matrices

$$
A =
\begin{bmatrix}
0 & 1 & -2.3 & 0.1 \\
1.3 & 4 & -0.1 & 0 \\
4.1 & -1 & 0 & 1.7
\end{bmatrix}
$$

**Explanation:**

A **matrix** is a rectangular array of numbers. The **size** is given by the number of rows and columns ($m \times n$).
Each entry $A_{ij}$ is identified by its row index $i$ and column index $j$.

**Matrix types:**
- **Square matrix**: same number of rows and columns ($n \times n$)
- **Tall matrix**: more rows than columns ($m > n$)
- **Wide matrix**: more columns than rows ($n > m$)

An $m \times n$ matrix can be viewed as columns concatenated or rows stacked.
A **submatrix** $A_{p:q,\,r:s}$ is formed by selecting specific rows and columns.

**Example:**

If

$$
B =
\begin{bmatrix}
0 & 1 & -2.3 & 0.1 \\
1.3 & 4 & -0.1 & 0 \\
4.1 & -1 & 0 & 1.7
\end{bmatrix},
$$

then $B_{13} = -2.3$, $B_{32} = -1$.

In [1]:
import numpy as np

matrix_a = np.array([
    [0, 1, -2.3, 0.1],
    [1.3, 4, -0.1, 0],
    [4.1, -1, 0, 1.7]
])

print("Matrix A:\n", matrix_a)
print("\nShape (rows × cols):", matrix_a.shape)
print("\nA[1,3] =", matrix_a[0, 2])
print("A[3,2] =", matrix_a[2, 1])
print("\nFirst row:", matrix_a[0, :])
print("Second column:\n", matrix_a[:, 1])
print("\nSubmatrix A[2:3, 3:4]:\n", matrix_a[1:3, 2:4])

Matrix A:
 [[ 0.   1.  -2.3  0.1]
 [ 1.3  4.  -0.1  0. ]
 [ 4.1 -1.   0.   1.7]]

Shape (rows × cols): (3, 4)

A[1,3] = -2.3
A[3,2] = -1.0

First row: [ 0.   1.  -2.3  0.1]
Second column:
 [ 1.  4. -1.]

Submatrix A[2:3, 3:4]:
 [[-0.1  0. ]
 [ 0.   1.7]]


**References:**


[📘 Boyd, S., & Vandenberghe, L. (2018). *Introduction to Applied Linear Algebra: Vectors, Matrices, and Least Squares.*](https://web.stanford.edu/~boyd/vmls/)



---



[⬅️ Previous: Basis](./05_basis.ipynb) | [Next: Linearity ➡️](./07_linearity.ipynb)
