### 1.1.1.3 Vectors

A **vector** is an ordered finite list of numbers. Vectors are typically represented as vertical arrays enclosed in square or curved brackets:

$$
\begin{bmatrix}
-1.1 \\
0.0 \\
3.6 \\
-7.2
\end{bmatrix}
\quad \text{or} \quad
\begin{pmatrix}
-1.1 \\
0.0 \\
3.6 \\
-7.2
\end{pmatrix}
$$

They may also be written as numbers separated by commas and surrounded by parentheses:

$$
(-1.1, 0.0, 3.6, -7.2)
$$

The *elements* (or *entries, coefficients, components*) of a vector are the values in the array.  
The **size** (also called *dimension* or *length*) of the vector is the number of elements it contains.  
For instance, the vector above has size four, and its third entry is $3.6$.  
A vector of size $n$ is called an *n-vector*. A 1-vector is considered to be the same as a scalar.

---

#### Geometric Definition

A vector can be represented **geometrically** as an **oriented segment** (an arrow) having a **starting point** and an **end point**.  

If $A$ and $B$ are two distinct points, the vector $\overrightarrow{AB}$ possesses both a **length (norm)** and a **direction**.

If the coordinates of both points $A$ and $B$ in the basis  
$$
b = (\vec{e}_1, \vec{e}_2, \vec{e}_3)
$$  
are respectively:

$$
A =
\begin{bmatrix}
x_A \\
y_A \\
z_A
\end{bmatrix}_b,
\quad
B =
\begin{bmatrix}
x_B \\
y_B \\
z_B
\end{bmatrix}_b,
$$

then the vector $\overrightarrow{AB}$ is expressed as:

$$
\overrightarrow{AB} =
\begin{bmatrix}
x_B - x_A \\
y_B - y_A \\
z_B - z_A
\end{bmatrix}_b
$$

It is also evident that:

$$
\overrightarrow{AB} = -\overrightarrow{BA}
$$

<p align="center">
  <img src="../../../Figures/01010103_vector_geometric_def.png"
       alt="Geometric definition of a vector as an oriented segment from A to B"
       width="400">
</p>



---

#### Real Vectors

The values of the elements in a vector are called **scalars**.  
In most applications, these are *real numbers* — such vectors are called **real vectors**.  

$$
a \in \mathbf{R}^n
$$

The set of all real numbers is denoted by $\mathbf{R}$, and the set of all real $n$-vectors by $\mathbf{R}^n$.  
Thus, $a \in \mathbf{R}^n$ means $a$ is an element of $\mathbf{R}^n$.

---

#### Block or Stacked Vectors

Vectors can be defined by concatenating or stacking multiple vectors:

$$
a =
\begin{bmatrix}
b \\
c \\
d
\end{bmatrix}
$$

If $b$, $c$, and $d$ are vectors of sizes $m$, $n$, and $p$, respectively, then this defines an $(m + n + p)$-vector:

$$
a = (b_1, b_2, \ldots, b_m, c_1, c_2, \ldots, c_n, d_1, d_2, \ldots, d_p)
$$

Stacked vectors can include scalars. For example, if $a$ is a 3-vector,  
then $(1, a)$ is a 4-vector:

$$
(1, a_1, a_2, a_3)
$$

---

#### Subvectors

Subvectors or *slices* of $a$ can be defined using **colon notation**.  
If $a$ is a vector, then:

$$
a_{r:s} = (a_r, \ldots, a_s)
$$

The subscript $r:s$ is called the *index range*.  
If:

$$
b = a_{1:m}
$$

$$
c = a_{(m+1):(m+n)}
$$

$$
d = a_{(m+n+1):(m+n+p)}
$$

then:

$$
a = (b, c, d)
$$

For example, if:

$$
z = (1, -1, 2, 0)
$$

then:

$$
z_{2:3} = (-1, 2)
$$

---

#### Notational Conventions

Some authors distinguish between vectors and scalars by notation.  
Greek letters $(\alpha, \beta, \ldots)$ may denote scalars, and lowercase Roman letters $(a, x, f, \ldots)$ denote vectors.  
Vectors may also appear in **bold** ($\mathbf{a}$) or with **arrows above** ($\vec{a}$).  
These conventions vary, so context must clarify meaning.

---

#### Indexing

For a vector $a$, the $i$-th element is denoted $a_i$.  
In mathematical notation, $i$ runs from $1$ to $n$.  
When ambiguity arises (e.g., $a_i$ could mean the $i$-th element or $i$-th vector), the context clarifies usage.  
To refer to the $j$-th element of vector $a_i$, we write:

$$
(a_i)_j
$$

---

#### Zero Vectors

A **zero vector** has all elements equal to zero.  
It is sometimes denoted:

$$
0_n
$$

where $n$ is the size, or simply:

$$
0
$$

The notation $0$ is overloaded — it may represent scalars or zero vectors, depending on context.  
For instance, if $a$ is a 9-vector and $a = 0$, this implies $a$ is the zero vector of size 9.

---

#### Unit Vectors

A **unit vector** has all elements zero except one element equal to one.  
The $i$-th unit vector of size $n$ is denoted $e_i$.  
For example, for $n = 3$:

$$
e_1 =
\begin{bmatrix}
1 \\ 0 \\ 0
\end{bmatrix},
\quad
e_2 =
\begin{bmatrix}
0 \\ 1 \\ 0
\end{bmatrix},
\quad
e_3 =
\begin{bmatrix}
0 \\ 0 \\ 1
\end{bmatrix}
$$


In [3]:
import numpy as np

# Define example vectors
a = np.array([-1.1, 0.0, 3.6, -7.2])
b = np.array([1, -1, 2, 0])

# Define stacked vector
c = np.concatenate(([1], a))

# Subvector example
sub_b = b[1:3]  # corresponds to z_{2:3} = (-1, 2)

# Define unit vectors of size 3
e1 = np.array([1, 0, 0])
e2 = np.array([0, 1, 0])
e3 = np.array([0, 0, 1])

print("Vector a:", a)
print("Stacked vector (1, a):", c)
print("Subvector b[1:3]:", sub_b)
print("Unit vectors:\n", e1, "\n", e2, "\n", e3)


Vector a: [-1.1  0.   3.6 -7.2]
Stacked vector (1, a): [ 1.  -1.1  0.   3.6 -7.2]
Subvector b[1:3]: [-1  2]
Unit vectors:
 [1 0 0] 
 [0 1 0] 
 [0 0 1]


**References:**

[📘 Boyd, S. & Vandenberghe, L. (2018). *Introduction to Applied Linear Algebra: Vectors, Matrices, and Least Squares.*](https://web.stanford.edu/~boyd/vmls/)

[📗 Rozycki, P (2020) - *Notes from Computational Mechanics Program, École Centrale de Nantes*](https://www.ec-nantes.fr/study/masters/computational-mechanics)


---

[⬅️ Previous: Cartesian Plane](./02_cartesian_plane.ipynb) | [Next: Vector Addition ➡️](./01_vector_addition.ipynb)
