### 1.1.1.3. Vectors

$$
\vec{v} = v_1 \hat{e}_1 + v_2 \hat{e}_2 + v_3 \hat{e}_3
=
\begin{bmatrix}
v_1 \\
v_2 \\
v_3
\end{bmatrix}
$$

**Explanation:**

A **vector** is an ordered finite list of numbers. The *elements* of a vector are the values in the array.
The **size** (also called *dimension* or *length*) is the number of elements. A vector of size $n$ is an *n-vector*.

A vector can be represented geometrically as an oriented segment (an arrow) having a starting point and an end point:

$$
\overrightarrow{AB} =
\begin{bmatrix}
x_B - x_A \\
y_B - y_A \\
z_B - z_A
\end{bmatrix}
$$

<p align="center">
  <img src="../../../Figures/01010103_vector_geometric_def.png"
       alt="Geometric definition of a vector as an oriented segment from A to B"
       width="400">
</p>

**Block vectors** are formed by concatenating vectors. If $\mathbf{b}$, $\mathbf{c}$, and $\mathbf{d}$ are vectors of sizes $m$, $n$, and $p$, then stacking produces an $(m + n + p)$-vector.

**Subvectors** use colon notation: $a_{r:s} = (a_r, \ldots, a_s)$.

**Unit vectors** have all elements zero except one element equal to one:

$$
e_1 =
\begin{bmatrix}
1 \\ 0 \\ 0
\end{bmatrix},
\quad
e_2 =
\begin{bmatrix}
0 \\ 1 \\ 0
\end{bmatrix},
\quad
e_3 =
\begin{bmatrix}
0 \\ 0 \\ 1
\end{bmatrix}
$$

**Example:**

If $z = (1, -1, 2, 0)$, then $z_{2:3} = (-1, 2)$.

In [ ]:
import numpy as np

vector_a = np.array([-1.1, 0.0, 3.6, -7.2])
vector_b = np.array([1, -1, 2, 0])

stacked = np.concatenate(([1], vector_a))

subvector = vector_b[1:3]

unit_e1 = np.array([1, 0, 0])
unit_e2 = np.array([0, 1, 0])
unit_e3 = np.array([0, 0, 1])

print("Vector a:", vector_a)
print("Stacked (1, a):", stacked)
print("Subvector b[1:3]:", subvector)
print("Unit vectors:\n", unit_e1, "\n", unit_e2, "\n", unit_e3)

Vector a: [-1.1  0.   3.6 -7.2]
Stacked vector (1, a): [ 1.  -1.1  0.   3.6 -7.2]
Subvector b[1:3]: [-1  2]
Unit vectors:
 [1 0 0] 
 [0 1 0] 
 [0 0 1]


**References:**


[📘 Boyd, S. & Vandenberghe, L. (2018). *Introduction to Applied Linear Algebra: Vectors, Matrices, and Least Squares.*](https://web.stanford.edu/~boyd/vmls/)



[📗 Rozycki, P (2020) - *Notes from Computational Mechanics Program, École Centrale de Nantes*](https://www.ec-nantes.fr/study/masters/computational-mechanics)





---



[⬅️ Previous: Cartesian Plane](./02_cartesian_plane.ipynb) | [Next: Euclidean Space ➡️](./04_euclidean_space.ipynb)
