### 1.1.1.6 Matrices


$$
A =
\begin{bmatrix}
0 & 1 & -2.3 & 0.1 \\
1.3 & 4 & -0.1 & 0 \\
4.1 & -1 & 0 & 1.7
\end{bmatrix}
$$


**Explanation:**

A **matrix** is a rectangular array of numbers written between square brackets or parentheses.  
The **size** (or **dimension**) of a matrix is given by the number of rows and columns.  
For example, the matrix above has 3 rows and 4 columns, so its size is $3 \times 4$.  
A general matrix of size $m \times n$ is called an **$m$-by-$n$ matrix**.

Each entry in a matrix is called an **element**, **entry**, or **coefficient**.  
The element in the $i$-th row and $j$-th column is denoted $A_{ij}$.  
The indices $i$ and $j$ are called the **row** and **column indices**, respectively.  
If $A$ is an $m \times n$ matrix, then $i$ runs from $1$ to $m$ and $j$ runs from $1$ to $n$.

Two matrices are equal if they have the same size and identical entries in corresponding positions.  
The set of all real $m \times n$ matrices is denoted $\mathbf{R}^{m \times n}$.

---

**Matrix Indexing**

If

$$
B =
\begin{bmatrix}
0 & 1 & -2.3 & 0.1 \\
1.3 & 4 & -0.1 & 0 \\
4.1 & -1 & 0 & 1.7
\end{bmatrix},
$$

then $B_{13} = -2.3$, $B_{32} = -1$.  
The row index of the bottom-left element (value $4.1$) is 3, and its column index is 1.

---

**Matrix Types**

- A **square matrix** has the same number of rows and columns ($n \times n$).  
- A **tall matrix** has more rows than columns ($m > n$).  
- A **wide matrix** has more columns than rows ($n > m$).  

A **row vector** is a $1 \times n$ matrix, and a **column vector** is an $n \times 1$ matrix.  
A **$1 \times 1$ matrix** is considered the same as a scalar.

Example:

$$
\text{Row vector: } [-2.1 \;\; -3 \;\; 0]
$$

$$
\text{Column vector: }
\begin{bmatrix}
2 \\
5
\end{bmatrix}
$$

---

**Columns and Rows of a Matrix**

An $m \times n$ matrix $A$ can be expressed in terms of its $n$ columns:

$$
a_j =
\begin{bmatrix}
A_{1j} \\
\vdots \\
A_{mj}
\end{bmatrix},
\quad j = 1, \ldots, n
$$

and its $m$ rows:

$$
b_i = [A_{i1} \; A_{i2} \; \cdots \; A_{in}],
\quad i = 1, \ldots, m
$$

For example,

$$
A =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

has first row $[1 \; 2 \; 3]$ and second column
$
\begin{bmatrix}
2 \\
5
\end{bmatrix}.
$

---

**Block Matrices and Submatrices**

A **block matrix** is a matrix whose entries are themselves matrices:

$$
A =
\begin{bmatrix}
B & C \\
D & E
\end{bmatrix}
$$

where $B$, $C$, $D$, and $E$ are called **blocks** or **submatrices** of $A$.  
Blocks in the same row must have the same number of rows, and blocks in the same column must have the same number of columns.  
Blocks placed side-by-side are said to be *concatenated*, and those stacked vertically are *stacked*.

Example:

$$
B = [0\ 2\ 3], \quad
C = [-1], \quad
D =
\begin{bmatrix}
2 & 2 & 1 \\
1 & 3 & 5
\end{bmatrix}, \quad
E =
\begin{bmatrix}
4 \\
4
\end{bmatrix}.
$$

Then

$$
A =
\begin{bmatrix}
0 & 2 & 3 & -1 \\
2 & 2 & 1 & 4 \\
1 & 3 & 5 & 4
\end{bmatrix}.
$$

---

**Submatrices**

A **submatrix** is formed by selecting specific rows and columns of a matrix.  
If $A$ is $m \times n$, then for integers $1 \leq p \leq q \leq m$ and $1 \leq r \leq s \leq n$,  
the submatrix $A_{p:q,\,r:s}$ is defined as:

$$
A_{p:q,\,r:s} =
\begin{bmatrix}
A_{pr} & \cdots & A_{ps} \\
\vdots & \ddots & \vdots \\
A_{qr} & \cdots & A_{qs}
\end{bmatrix}.
$$

Example:

$$
A_{2:3,\,3:4} =
\begin{bmatrix}
1 & 4 \\
5 & 4
\end{bmatrix}.
$$

---

**Column and Row Representation**

An $m \times n$ matrix $A$ can also be written as a concatenation of its $n$ column vectors:

$$
A = [\, a_1 \; a_2 \; \cdots \; a_n \,],
$$

or equivalently, as a stack of its $m$ row vectors:

$$
A =
\begin{bmatrix}
b_1 \\[3pt]
b_2 \\[3pt]
\vdots \\[3pt]
b_m
\end{bmatrix}.
$$

Thus, a matrix can be viewed as either **columns concatenated** or **rows stacked**.


In [7]:
import numpy as np

# Define a 3x4 matrix
A = np.array([
    [0, 1, -2.3, 0.1],
    [1.3, 4, -0.1, 0],
    [4.1, -1, 0, 1.7]
])

print("Matrix A:\n", A)
print("\nShape (rows x cols):", A.shape)

# Access elements (theoretical 1-based indexing → NumPy 0-based)
print("\nA[1,3] =", A[0, 2])
print("A[3,2] =", A[2, 1])

# Extract row and column
print("\nFirst row:", A[0, :])
print("Second column:\n", A[:, 1])

# Extract submatrix (rows 2–3, cols 3–4)
print("\nSubmatrix A[2:3, 3:4]:\n", A[1:3, 2:4])


Matrix A:
 [[ 0.   1.  -2.3  0.1]
 [ 1.3  4.  -0.1  0. ]
 [ 4.1 -1.   0.   1.7]]

Shape (rows x cols): (3, 4)

A[1,3] = -2.3
A[3,2] = -1.0

First row: [ 0.   1.  -2.3  0.1]
Second column:
 [ 1.  4. -1.]

Submatrix A[2:3, 3:4]:
 [[-0.1  0. ]
 [ 0.   1.7]]


**References:**

[📘 Boyd, S., & Vandenberghe, L. (2018). *Introduction to Applied Linear Algebra: Vectors, Matrices, and Least Squares.*](https://web.stanford.edu/~boyd/vmls/)

---

[⬅️ Previous: Basis](./05_basis.ipynb) | [Next: Change of Basis ➡️](./07_change_of_basis.ipynb)
