### 1.1.7.1.2. Definitions

$$
\begin{aligned}
& A \in \mathbb{R}^{n \times n} \\
& \text{eig}(A) = (\lambda_1, \lambda_2, \ldots, \lambda_n) \\
& p(\lambda) = \det(A - \lambda \mathbb{1}) \\
& \Lambda = \text{diag}(\lambda_1, \lambda_2, \ldots, \lambda_n) \\
& Q = [\vec{e}_{\lambda_1} | \vec{e}_{\lambda_2} | \cdots | \vec{e}_{\lambda_n}] \\
& A = Q \Lambda Q^{-1} \\
& \Lambda = Q^{-1} A Q
\end{aligned}
$$

**Explanation:**

The eigenvalues $\lambda_i$ are the roots of the characteristic polynomial $p(\lambda) = \det(A - \lambda \mathbb{1})$.
Each eigenvalue has an associated eigenvector $\vec{e}_{\lambda_i}$ satisfying $A \vec{e}_{\lambda_i} = \lambda_i \vec{e}_{\lambda_i}$.
The matrix $\Lambda$ is the diagonal matrix of eigenvalues, and $Q$ is the change-of-basis matrix whose columns are the eigenvectors, transforming from the eigenbasis to the standard basis.

**Example:**

If

$$
A = \begin{bmatrix} 1 & 2 & 0 \\ 0 & 3 & 0 \\ 2 & -4 & 2 \end{bmatrix},
$$

then the eigenvalues are $\lambda_1 = 3$, $\lambda_2 = 2$, $\lambda_3 = 1$.

In [2]:
import numpy as np

matrix_a = np.array([[1, 2, 0],
                     [0, 3, 0],
                     [2, -4, 2]], dtype=float)

dimension = matrix_a.shape[0]
identity = np.eye(dimension)

sample_points = np.linspace(-1, 5, dimension + 1)
det_samples = np.array([np.linalg.det(matrix_a - lam * identity) for lam in sample_points])
polynomial_coefficients = np.polyfit(sample_points, det_samples, dimension)
eigenvalues = np.sort(np.real(np.roots(polynomial_coefficients)))[::-1]

print("Eigenvalues:", np.round(eigenvalues, 10))

eigenvectors_list = []
for eigenvalue in eigenvalues:
    shifted = matrix_a - eigenvalue * identity
    _, _, right_singular = np.linalg.svd(shifted)
    eigenvector = right_singular[-1]
    eigenvectors_list.append(eigenvector / np.linalg.norm(eigenvector))

eigenvectors_q = np.column_stack(eigenvectors_list)
lambda_diag = np.diag(eigenvalues)
q_inverse = np.linalg.inv(eigenvectors_q)

print("\nEigenvector matrix Q:")
print(np.round(eigenvectors_q, 10))
print("\nΛ (diagonal matrix of eigenvalues):")
print(np.round(lambda_diag, 10))

reconstructed_a = eigenvectors_q @ lambda_diag @ q_inverse
print("\nQ Λ Q⁻¹ (should equal A):")
print(np.round(reconstructed_a, 10))

print("\n--- Library method ---")
eigenvalues_lib, eigenvectors_lib = np.linalg.eig(matrix_a)
print("Eigenvalues:", np.round(eigenvalues_lib, 10))
print("Eigenvector matrix Q:")
print(np.round(eigenvectors_lib, 10))

Eigenvalues: [3. 2. 1.]

Eigenvector matrix Q:
[[ 0.40824829 -0.         -0.4472136 ]
 [ 0.40824829 -0.         -0.        ]
 [-0.81649658  1.          0.89442719]]

Λ (diagonal matrix of eigenvalues):
[[3. 0. 0.]
 [0. 2. 0.]
 [0. 0. 1.]]

Q Λ Q⁻¹ (should equal A):
[[ 1.  2. -0.]
 [-0.  3. -0.]
 [ 2. -4.  2.]]

--- Library method ---
Eigenvalues: [2. 1. 3.]
Eigenvector matrix Q:
[[ 0.          0.4472136   0.40824829]
 [ 0.          0.          0.40824829]
 [ 1.         -0.89442719 -0.81649658]]


**References:**

[📘 Savov, I. (2016). *No Bullshit Guide to Linear Algebra*, Section 7.1.](https://minireference.com/static/excerpts/noBSLA_v2_preview.pdf)

---

[⬅️ Previous: Eigenvalues and Eigenvectors](./01_eigenvalues_and_eigenvectors.ipynb) | [Next: Eigenvalues ➡️](./03_eigenvalues.ipynb)