### 1.1.7.1.5. Eigendecomposition

$$
A = Q \Lambda Q^{-1}
$$

$$
\Lambda = Q^{-1} A Q
$$

**Explanation:**

If $A$ has $n$ linearly independent eigenvectors, it is diagonalizable and admits the eigendecomposition $A = Q \Lambda Q^{-1}$.
This writes $A$ in its eigenbasis: first $Q^{-1}$ transforms to the eigenbasis, then $\Lambda$ scales each component by its eigenvalue, and finally $Q$ transforms back to the standard basis.
Only the direction of eigenvectors matters — any non-zero scalar multiple of an eigenvector is also an eigenvector.

**Example:**

For

$$
A = \begin{bmatrix} 1 & 2 & 0 \\ 0 & 3 & 0 \\ 2 & -4 & 2 \end{bmatrix},
$$

the eigendecomposition $A = Q \Lambda Q^{-1}$ can be computed and verified by reconstructing $A$ from $Q$, $\Lambda$, and $Q^{-1}$.

In [ ]:
import numpy as np

matrix_a = np.array([[1, 2, 0],
                     [0, 3, 0],
                     [2, -4, 2]], dtype=float)

dimension = matrix_a.shape[0]
identity = np.eye(dimension)

sample_points = np.linspace(-1, 5, dimension + 1)
det_samples = np.array([np.linalg.det(matrix_a - lam * identity) for lam in sample_points])
polynomial_coefficients = np.polyfit(sample_points, det_samples, dimension)
eigenvalues = np.sort(np.real(np.roots(polynomial_coefficients)))[::-1]

eigenvectors_list = []
for eigenvalue in eigenvalues:
    shifted = matrix_a - eigenvalue * identity
    _, _, right_singular = np.linalg.svd(shifted)
    eigenvector = right_singular[-1]
    eigenvectors_list.append(eigenvector / np.linalg.norm(eigenvector))

eigenvectors_q = np.column_stack(eigenvectors_list)
lambda_diag = np.diag(eigenvalues)
q_inverse = np.linalg.inv(eigenvectors_q)

print("Q (eigenvector matrix):")
print(np.round(eigenvectors_q, 10))
print("\nΛ (eigenvalue diagonal matrix):")
print(np.round(lambda_diag, 10))
print("\nQ⁻¹:")
print(np.round(q_inverse, 10))

reconstructed_a = eigenvectors_q @ lambda_diag @ q_inverse
print("\nQ Λ Q⁻¹ (should equal A):")
print(np.round(reconstructed_a, 10))
print("Reconstruction matches A:", np.allclose(matrix_a, reconstructed_a))

print("\n--- Library method ---")
eigenvalues_lib, eigenvectors_lib = np.linalg.eig(matrix_a)
print("Eigenvalues:", np.round(eigenvalues_lib, 10))
reconstruction_lib = eigenvectors_lib @ np.diag(eigenvalues_lib) @ np.linalg.inv(eigenvectors_lib)
print("Reconstruction matches A:", np.allclose(matrix_a, reconstruction_lib))

Q (eigenvector matrix):
[[ 0.          0.4472136   0.40824829]
 [ 0.          0.          0.40824829]
 [ 1.         -0.89442719 -0.81649658]]

Λ (eigenvalue diagonal matrix):
[[2. 0. 0.]
 [0. 1. 0.]
 [0. 0. 3.]]

Q⁻¹:
[[ 2.          0.          1.        ]
 [ 2.23606798 -2.23606798  0.        ]
 [ 0.          2.44948974  0.        ]]

Q Λ Q⁻¹ (should equal A):
[[ 1.  2.  0.]
 [ 0.  3.  0.]
 [ 2. -4.  2.]]

Reconstruction matches A: True


**References:**

[📘 Savov, I. (2016). *No Bullshit Guide to Linear Algebra*, Section 7.1.](https://minireference.com/static/excerpts/noBSLA_v2_preview.pdf)

---

[⬅️ Previous: Eigenvectors](./04_eigenvectors.ipynb) | [Next: Eigenspaces ➡️](./06_eigenspaces.ipynb)