### 1.1.7.1.11. Normal Matrices Eigendecomposition

$$
A^{\mathsf{T}}A = AA^{\mathsf{T}}, \qquad A = O\Lambda O^{\mathsf{T}}, \qquad O^{-1} = O^{\mathsf{T}}
$$

**Explanation:**

A normal matrix satisfies $A^{\mathsf{T}}A = AA^{\mathsf{T}}$. Its eigenvectors corresponding to distinct eigenvalues are orthogonal. Using orthonormal eigenvectors as columns of an orthogonal matrix $O$, the eigendecomposition simplifies to $A = O\Lambda O^{\mathsf{T}}$ since $O^{-1} = O^{\mathsf{T}}$.

All symmetric matrices are normal, so any real symmetric matrix admits this decomposition.

**Example:**

For the symmetric matrix

$$
A = \begin{bmatrix} 9 & -2 \\ -2 & 6 \end{bmatrix}
$$

the eigenvectors $\vec{e}_{\lambda_1}$ and $\vec{e}_{\lambda_2}$ are orthogonal, so we can normalize them into $O$ and verify:

$$
O^{\mathsf{T}} O = I, \qquad O \Lambda O^{\mathsf{T}} = A
$$

In [ ]:
import numpy as np

matrix_a = np.array([[9, -2],
                     [-2,  6]], dtype=float)

print("AᵀA == AAᵀ (normal):", np.allclose(matrix_a.T @ matrix_a, matrix_a @ matrix_a.T))

trace = matrix_a[0, 0] + matrix_a[1, 1]
determinant = matrix_a[0, 0] * matrix_a[1, 1] - matrix_a[0, 1] * matrix_a[1, 0]
eigenvalues = np.sort(np.roots([1, -trace, determinant]))

identity = np.eye(2)
eigenvectors_list = []
for eigenvalue in eigenvalues:
    shifted = matrix_a - eigenvalue * identity
    if np.abs(shifted[0, 0]) > 1e-10:
        eigenvector = np.array([-shifted[0, 1] / shifted[0, 0], 1.0])
    else:
        eigenvector = np.array([1.0, 0.0])
    eigenvectors_list.append(eigenvector / np.linalg.norm(eigenvector))

orthogonal_matrix = np.column_stack(eigenvectors_list)
lambda_diagonal = np.diag(eigenvalues)

orthogonality_check = orthogonal_matrix.T @ orthogonal_matrix
reconstruction = orthogonal_matrix @ lambda_diagonal @ orthogonal_matrix.T

print("Eigenvalues:", eigenvalues)
print("\nOrthogonal matrix O:")
print(np.round(orthogonal_matrix, 4))
print("\nOᵀO (should be I):")
print(np.round(orthogonality_check, 4))
print("\nOΛOᵀ (should be A):")
print(np.round(reconstruction, 4))
print("Reconstruction matches A:", np.allclose(matrix_a, reconstruction))

print("\n--- Library method ---")
eigenvalues_lib, orthogonal_lib = np.linalg.eigh(matrix_a)
print("Eigenvalues:", eigenvalues_lib)
print("OᵀO:", np.round(orthogonal_lib.T @ orthogonal_lib, 4))

Eigenvalues: [ 5. 10.]

Orthogonal matrix O:
[[-0.4472 -0.8944]
 [-0.8944  0.4472]]

OᵀO (should be I):
[[1. 0.]
 [0. 1.]]

OΛOᵀ (should be A):
[[ 9. -2.]
 [-2.  6.]]


**References:**

[📘 Savov, I. (2016). *No Bullshit Guide to Linear Algebra*, Section 7.1](https://minireference.com/)

---

[⬅️ Previous: Relation to Invertibility](./10_relation_to_invertibility.ipynb) | [Next: Non-Diagonalizable Matrices ➡️](./12_non_diagonalizable_matrices.ipynb)