### 1.1.2.10. Inverse of a Square Matrix

  

$$
\mathbf{A}^{-1} = \frac{1}{\det(\mathbf{A})} \, \text{adj}(\mathbf{A}), 
\quad
\det(\mathbf{A}) \neq 0
$$

 
**Explanation:**

  

The inverse of a square matrix generalizes the process for higher dimensions using the adjugate and determinant.  
It is crucial in linear algebra and ML for solving systems of equations.



**Steps:**

1. **Determinant Calculation:**  
   If the **determinant is null**, the **matrix is not invertible**.

2. **Cofactor Matrix:**  
   Compute the determinant of the cofactor matrix associated with $\mathbf{A}$,  
   multiplying each minor by $(-1)^{i+j}$, where *i* is the row and *j* the column.

3. **Adjugate and Final Inverse:**  
   Take the **transpose** of the cofactor matrix (the adjugate matrix)  
   and divide by the determinant to obtain $\mathbf{A}^{-1}$.


#### **Example: Inverse of 3×3 Matrix**

  

Let  

$$
\mathbf{A} =
\begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i
\end{bmatrix}
$$

  

**1st step**

$$
\det(\mathbf{A}) = aei + bfg + cdh - gec - hfa - idb \neq 0
$$

  

**2nd step**

For $i = 1$ and $j = 1$ (deletion of the first row and column):

$$
\mathbf{A} =
\begin{bmatrix}
\color{red}{a} & \color{red}{b} & \color{red}{c} \\
\color{red}{d} & e & f \\
\color{red}{g} & h & i
\end{bmatrix}
\Rightarrow
(-1)^{1+1}
\begin{vmatrix}
e & f \\
h & i
\end{vmatrix}
=
\begin{vmatrix}
e & f \\
h & i
\end{vmatrix}
$$

  

For $i = 1$ and $j = 2$ (deletion of the first row and second column):

$$
\mathbf{A} =
\begin{bmatrix}
\color{red}{a} & \color{red}{b} & \color{red}{c} \\
d & \color{red}{e} & f \\
g & \color{red}{h} & i
\end{bmatrix}
\Rightarrow
(-1)^{1+2}
\begin{vmatrix}
d & f \\
g & i
\end{vmatrix}
=
-
\begin{vmatrix}
d & f \\
g & i
\end{vmatrix}
$$

and so on for the remaining cofactors.


**3rd step**

  

$$
\mathbf{A}^{-1} = 
\frac{1}{\det(\mathbf{A})}
\begin{bmatrix}
\begin{vmatrix} e & f \\ h & i \end{vmatrix} &
-\begin{vmatrix} d & f \\ g & i \end{vmatrix} &
\begin{vmatrix} d & e \\ g & h \end{vmatrix} \\
-\begin{vmatrix} b & c \\ h & i \end{vmatrix} &
\begin{vmatrix} a & c \\ g & i \end{vmatrix} &
-\begin{vmatrix} a & b \\ g & h \end{vmatrix} \\
\begin{vmatrix} b & c \\ e & f \end{vmatrix} &
-\begin{vmatrix} a & c \\ d & f \end{vmatrix} &
\begin{vmatrix} a & b \\ d & e \end{vmatrix}
\end{bmatrix}^T
$$

  

Thus,

  

$$
\mathbf{A}^{-1} = 
\frac{1}{\det(\mathbf{A})}
\begin{bmatrix}
\begin{vmatrix} e & f \\ h & i \end{vmatrix} &
-\begin{vmatrix} b & c \\ h & i \end{vmatrix} &
\begin{vmatrix} b & c \\ e & f \end{vmatrix} \\
-\begin{vmatrix} d & f \\ g & i \end{vmatrix} &
\begin{vmatrix} a & c \\ g & i \end{vmatrix} &
-\begin{vmatrix} a & c \\ d & f \end{vmatrix} \\
\begin{vmatrix} d & e \\ g & h \end{vmatrix} &
-\begin{vmatrix} a & b \\ g & h \end{vmatrix} &
\begin{vmatrix} a & b \\ d & e \end{vmatrix}
\end{bmatrix}
$$


#### **Numerical Example**


Let  

$$
\mathbf{A} =
\begin{bmatrix}
2 & 1 & 0 \\
1 & 2 & 1 \\
0 & 1 & 2
\end{bmatrix}
$$

  

**1st step**

Using $\,\det(\mathbf{A}) = aei + bfg + cdh - gec - hfa - idb\,$:

$$
\det(\mathbf{A}) = (2)(2)(2) + (1)(1)(0) + (0)(1)(1)
- (0)(2)(0) - (1)(1)(2) - (2)(1)(1) = 8 - 2 - 2 = 4 \neq 0.
$$

  

**2nd step**

For $i=1,\ j=1$ (delete first row and first column):

$$
\mathbf{A} =
\begin{bmatrix}
\color{red}{2} & \color{red}{1} & \color{red}{0} \\
\color{red}{1} & 2 & 1 \\
\color{red}{0} & 1 & 2
\end{bmatrix}
\Rightarrow
\begin{vmatrix}
2 & 1 \\
1 & 2
\end{vmatrix}
= 3,
\qquad C_{11} = (+)3.
$$

  

For $i=1,\ j=2$ (delete first row and second column):

$$
\mathbf{A} =
\begin{bmatrix}
\color{red}{2} & \color{red}{1} & \color{red}{0} \\
1 & \color{red}{2} & 1 \\
0 & \color{red}{1} & 2
\end{bmatrix}
\Rightarrow
\begin{vmatrix}
1 & 1 \\
0 & 2
\end{vmatrix}
= 2,
\qquad C_{12} = (-)2 = -2.
$$

Proceeding similarly for all entries gives the **cofactor matrix**:

$$
\mathbf{C} =
\begin{bmatrix}
\;\,3 & -2 & \;\,1 \\
-2 & \;\,4 & -2 \\
\;\,1 & -2 & \;\,3
\end{bmatrix}.
$$

  

**3rd step**

The **adjugate** is the transpose of the cofactor matrix, here identical because $\mathbf{C}$ is symmetric:

$$
\operatorname{adj}(\mathbf{A}) = \mathbf{C}^T =
\begin{bmatrix}
3 & -2 & 1 \\
-2 & 4 & -2 \\
1 & -2 & 3
\end{bmatrix}.
$$

Therefore,

$$
\mathbf{A}^{-1}
= \frac{1}{\det(\mathbf{A})}\,\operatorname{adj}(\mathbf{A})
= \frac{1}{4}
\begin{bmatrix}
3 & -2 & 1 \\
-2 & 4 & -2 \\
1 & -2 & 3
\end{bmatrix}
=
\begin{bmatrix}
0.75 & -0.50 & 0.25 \\
-0.50 & 1.00 & -0.50 \\
0.25 & -0.50 & 0.75
\end{bmatrix}.
$$



In [ ]:
import numpy as np

# Define the 3×3 matrix
A = np.array([
    [2, 1, 0],
    [1, 2, 1],
    [0, 1, 2]
])

# Compute the inverse
result = np.linalg.inv(A)

print("A =\n", A)
print("\nA⁻¹ =\n", np.round(result, 4))

A =
 [[2 1 0]
 [1 2 1]
 [0 1 2]]

A⁻¹ =
 [[ 0.75 -0.5   0.25]
 [-0.5   1.   -0.5 ]
 [ 0.25 -0.5   0.75]]


**References:**

[📘 Aazi 2024 - *Mathematics For Machine Learning*](https://www.scribd.com/document/812294393/Mathematics-for-Machine-Learning)  
[📗 P. Rozycki - *Notes from Computational Mechanics Program, École Centrale de Nantes*](https://www.ec-nantes.fr/study/masters/computational-mechanics)

---

[⬅️ Previous: Determinant of a Triangular Matrix](./09_matrix_determinant.ipynb) | [Next: Rank–Nullity Theorem ➡️](./11_matrix_rank_nullity.ipynb)
