### 1.1.2.1. Vectors

$$
\vec{v} = v_1 \hat{e}_1 + v_2 \hat{e}_2 + v_3 \hat{e}_3
=
\begin{bmatrix}
v_1 \\
v_2 \\
v_3
\end{bmatrix}
$$

**Explanation:**

A **vector** is the mathematical representation of a physical entity characterized by magnitude (size) and direction.
A **scalar** is characterized by magnitude only (e.g., temperature, mass, energy).

A vector is depicted graphically as a directed line segment (an arrow). A collection of bound vectors at various points forms a **vector field**.

<p align="center">
  <img src="../../../Figures/01010201_vector_and_field.jpeg"
       alt="Graphical depiction of a vector (a) and a vector field (b)"
       width="500">
</p>

A vector can be anchored to the origin of a coordinate system and completely specified by the coordinates of its end point.

<p align="center">
  <img src="../../../Figures/01010201_vector_3d_cartesian.jpeg"
       alt="A vector in 3-D Cartesian coordinates"
       width="540">
</p>

The **size** (also called *dimension* or *length*) is the number of elements. A vector of size $n$ is an *n-vector*.

A vector can also be represented as an oriented segment from point $A$ to point $B$:

$$
\overrightarrow{AB} =
\begin{bmatrix}
x_B - x_A \\
y_B - y_A \\
z_B - z_A
\end{bmatrix}
$$

<p align="center">
  <img src="../../../Figures/01010201_vector_geometric_def.png"
       alt="Geometric definition of a vector as an oriented segment from A to B"
       width="350">
</p>

**Cartesian Unit Vectors:**

The unit vectors $\hat{\imath}$, $\hat{\jmath}$, $\hat{k}$ point in the directions of the $x$-, $y$-, and $z$-axes. They have magnitude exactly equal to one and can be drawn at any location — they indicate direction, not position.

<p align="center">
  <img src="../../../Figures/01010201_unit_vectors_cartesian.jpeg"
       alt="Unit vectors in 3-D Cartesian coordinates"
       width="300">
</p>

<p align="center">
  <img src="../../../Figures/01010201_unit_vectors_arbitrary_point.jpeg"
       alt="Cartesian unit vectors at an arbitrary point"
       width="300">
</p>

**Vector Components:**

The components of a vector are the projections of the vector onto the coordinate axes. Any vector $\vec{A}$ can be written as:

$$
\vec{A} = A_x \hat{\imath} + A_y \hat{\jmath} + A_z \hat{k}
$$

where $A_x$, $A_y$, $A_z$ are scalar magnitudes indicating how many unit steps to take along each axis direction.

<p align="center">
  <img src="../../../Figures/01010201_vector_components.jpeg"
       alt="Vector A and its components"
       width="500">
</p>

In 2D, the components can be found by projecting the vector onto the coordinate axes:

$$
A_x = |\vec{A}| \cos(\theta), \quad A_y = |\vec{A}| \sin(\theta)
$$

<p align="center">
  <img src="../../../Figures/01010201_vector_projections.jpeg"
       alt="Vector components as projections onto x- and y-axes"
       width="500">
</p>

**Block vectors** are formed by concatenating vectors. If $\mathbf{b}$, $\mathbf{c}$, and $\mathbf{d}$ are vectors of sizes $m$, $n$, and $p$, then stacking produces an $(m + n + p)$-vector.

**Subvectors** use colon notation: $a_{r:s} = (a_r, \ldots, a_s)$.

**Unit vectors** have all elements zero except one element equal to one:

$$
e_1 =
\begin{bmatrix}
1 \\ 0 \\ 0
\end{bmatrix},
\quad
e_2 =
\begin{bmatrix}
0 \\ 1 \\ 0
\end{bmatrix},
\quad
e_3 =
\begin{bmatrix}
0 \\ 0 \\ 1
\end{bmatrix}
$$

**Basis Vectors:**

Any set of linearly independent vectors that span a space can serve as **basis vectors**. The standard orthonormal basis $\hat{\imath}$, $\hat{\jmath}$, $\hat{k}$ is one choice, but non-unit or non-orthogonal bases are also valid as long as no vector in the set is a linear combination of the others.

<p align="center">
  <img src="../../../Figures/01010201_alternative_basis_vectors.jpeg"
       alt="Alternative basis vectors"
       width="500">
</p>

A unit vector can be formed from any non-zero vector by dividing by its magnitude:

$$
\hat{e} = \frac{\vec{e}}{|\vec{e}|}
$$

**Example:**

If $z = (1, -1, 2, 0)$, then $z_{2:3} = (-1, 2)$.

In [1]:
import numpy as np

vector_a = np.array([-1.1, 0.0, 3.6, -7.2])
vector_b = np.array([1, -1, 2, 0])

stacked = np.concatenate(([1], vector_a))

subvector = vector_b[1:3]

unit_e1 = np.array([1, 0, 0])
unit_e2 = np.array([0, 1, 0])
unit_e3 = np.array([0, 0, 1])

print("Vector a:", vector_a)
print("Stacked (1, a):", stacked)
print("Subvector b[1:3]:", subvector)
print("Unit vectors:\n", unit_e1, "\n", unit_e2, "\n", unit_e3)

Vector a: [-1.1  0.   3.6 -7.2]
Stacked (1, a): [ 1.  -1.1  0.   3.6 -7.2]
Subvector b[1:3]: [-1  2]
Unit vectors:
 [1 0 0] 
 [0 1 0] 
 [0 0 1]


**References:**

[📘 Boyd, S. & Vandenberghe, L. (2018). *Introduction to Applied Linear Algebra: Vectors, Matrices, and Least Squares.*](https://web.stanford.edu/~boyd/vmls/)

[📗 Fleisch, D. (2012). *A Student's Guide to Vectors and Tensors.* Cambridge University Press.](https://www.cambridge.org/core/books/students-guide-to-vectors-and-tensors/46EB80DBBF3C1C1B06F1B9E34C6D7753)

[📗 Rozycki, P. (2020). *Notes from Computational Mechanics Program, École Centrale de Nantes.*](https://www.ec-nantes.fr/study/masters/computational-mechanics)

---

[⬅️ Previous: Non-Cartesian Coordinate Systems](../01_Prerequisites/03_non_cartesian_coordinate_systems.ipynb) | [Next: Vector Addition ➡️](./02_vector_addition.ipynb)